<a href="https://colab.research.google.com/github/lavjachica/programacionpython-2024/blob/main/Laboratorio4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


A. Crear un array de 10 elementos. Los elementos de este array deben ser consecutivos
del 1 al 10. Este array no debe ser aleatorio

In [ ]:
arreglo = np.arange(1,11)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
type(arreglo)

numpy.ndarray

B. Crear un segundo array de 10 elementos. Este array si debe ser aleatorio. Los valores
deben ser enteros entre el 1 al 20.


In [ ]:
arreglo2= np.random.randint(1,21,10)
arreglo2

array([17,  8, 16, 20,  4, 20,  3, 13,  7,  1])

C. Obtener un vector único de 10 elementos, sumando los dos arrays anteriores.

In [ ]:
arreglo_sum = arreglo + arreglo2
arreglo_sum

array([18, 10, 19, 24,  9, 26, 10, 21, 16, 11])

D. Mezclar el vector obtenido en la letra C utilizando una función vista en la Unidad IV

In [ ]:
reordenar = np.random.shuffle(arreglo_sum)
reordenar

In [ ]:
arreglo_sum

array([24, 10, 26, 21, 16,  9, 10, 19, 11, 18])

E. Calcular la Mediana, el Promedio y Posiciones de Valores Máximo y Mínimo utilizando
las funciones vistas en la Unidad IV. Tomar el vector de la letra D.

In [ ]:
mediana = np.median(arreglo_sum)
mediana

17.0

In [ ]:
promedio = np.mean(arreglo_sum)
promedio

16.4

In [ ]:
posicion_valor_min = np.argmin(arreglo_sum)
posicion_valor_min

5

In [ ]:
posicion_valor_max = np.argmax(arreglo_sum)
posicion_valor_max


2

E. Transformar el vector obtenido en una Matriz de 2 x 5


In [ ]:
matriz = np.reshape(arreglo_sum,(2,5))
matriz

array([[24, 10, 26, 21, 16],
       [ 9, 10, 19, 11, 18]])